apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: basketball
  namespace: basketball
spec:
  network:
    expose:
      - service: basketball-frontend
        selector:
          app: frontend
        gateway: tenant
        host: basketball
        port: 80
    allow:
      - direction: Ingress
        selector:
          app: backend
        port: 3000